version: '3'

services:
    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        volumes:
            - ./frontend:/usr/src/app
            - /usr/src/app/node_modules
        ports:
            - 3000:3000
    backend:
        build:
            context: ./backend/Api
            dockerfile: Dockerfile
        volumes:
            - ./backend:/app/publish
        ports:
            - 5001:5000
    # db:
    #     image: 'mcr.microsoft.com/mssql/server'
    #     environment:
    #         SA_PASSWORD: 'Your_password123'
    #         ACCEPT_EULA: 'Y'
    #     ports:
    #         - '3306:3306'
    #     volumes:
    #         - db-data:/var/opt/mssql
